name: edu_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider:
  cached_network_image: ^3.3.1 # ✅ أضف هذه الحزمة
  smooth_page_indicator: ^1.1.0 # أو أي إصدار أحدث


  # State & Local DB
  get: ^4.6.6
  sqflite: ^2.3.3
  path: ^1.8.3
  get_storage: ^2.1.1

  # Firebase



  image_picker: ^1.1.2

  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.5
  firebase_auth: ^4.20.0 # <-- الحزمة الجديدة
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
